---
env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
settings:
  import/resolver:
    node:
      extensions:
        - .ts
rules:
  prettier/prettier: error
  import/prefer-default-export: off
  import/extensions:
    - error
    - ignorePackages
    -
      ts: never
  no-useless-constructor: off
  '@typescript-eslint/explicit-module-boundary-types': off